### ISSUE TITLE
The secret-token cannot be dynamic

### ISSUE THREAD

**Issue by jeffwillden** [ptejada/artillery-engine-socketio-v3#10]
```
config:
  payload:
    path: "credentials.csv"
    fields:
      - "secretToken"
  engines:
    socketio-v3:
      parser: msgpack
      query:
        token: {{ secretToken }}
```
This plugin does not support getting a `secretToken` from `context.vars` or from a `credentials.csv` file. It only supports a single hard-coded token for one user. If an app follows best practices and requires a token up front in order to establish the connection, then this plugin only supports a single user. You can have many different instances of that user, but they all must be the same user. For apps where this is considered a security violation, (one connection per user) then this design flaw is a showstopper. Anybody know a way around this limitation?

I tried using the `reconnect:true` option, but it still has to reconnect using the hard-coded secretToken instead of a dynamic value as implied in the (non-functional) code above.
