### ISSUE TITLE
acknowledge failed

### ISSUE THREAD

**Issue by exodia0x** [ptejada/artillery-engine-socketio-v3#12]
```
          acknowledge:
          capture:
            json: "$.protocol"
            as: "ack"
      - log: "Acknowledgement == {{ack}}"
```
      
Form the code I When i emit message with ' channel : "command" and event: "command"'. I got message `"Acknowledgement == {"value":"","failed":true}"` but i check socket.io server emit was success. How to Fix it this is example acknowledge result with json type
      
```
      {
    "protocol": {
        "version": "1",
        "command": "ack",
        "invoke": "1",
        "qos": "normal",
    }
}
```

**Comment by ptejada** [comment]
Can you include more lines about your example? Like the full emit action from the yml example.

Any snippet of the equivalent JS client and server actions you are trying to test might be helpful as well.

**Comment by exodia0x** [comment]
Example Artillery code. emit data with json type

```
config:
  target: "https://Domain.com"
  phases:
    - duration: 1
      arrivalRate: 1
  engines:
   socketio-v3:
    extraHeaders: 
      key: "Testing"
    transports: ["websocket"]

scenarios:
  - name: " > Send Message and Check Respond == ACT scenario"
    engine: socketio-v3
    flow:
      - emit:
          channel: "command"
          event: "command"
          data:
            protocol:
              version: "1"
              command: "service"
              subCommand: "init1"
              invoke: "1234"
              qos: "test"
              topic: "test123"
              token: "token1234"
              service: "ODA"
              diagMessage: ""
            header:
              version: "1.0"
              timestamp: "2023-05-01T14:51:06.157Z"
              orgService: "1234"
              tid: "1234"
              lastTid: "1234"
              session: "1234"
              transaction: "1234"
              communication: "unicast"
              groupTags: []
              identity:
                device: "1234"
              tmfSpec: "1234"
              baseApiVersion: "1234"
              schemaVersion: "1234"
            body: {}
        acknowledge:
          capture:
            json: "$.protocol"
            as: "ack"
      - log: "Acknowledgement == {{ack}}"
```


Server Script i cant show it.

**Comment by ptejada** [comment]
Hello,

An easy way to troubleshoot this is to print or log the data your receiving on your server. I didn't mean for you to share your whole server code, but at least how you are listening for the event. 

Another thing you can try is capturing everything to see what you are getting back:
```yml
   capture:
       json: "$"
       as: "ack"
```
Then you can log the `{{ack}}` like you were doing.

About your `emit` action, the `emit.event` setting is not a valid option so it won't be sent to server. Only `emit.channel` and `emit.data` will be sent. With that being said this two explicit options are part of the legacy API. Use the array syntax instead, which allows you to send as many arguments as your want.

For example, if this is how you are listening to the event on the server
```
socket.on('command', (event, data, ack) => ack(data))
```

Then you want to send three separate params to the server. Ex:

```yml
...
      - emit:
          - command
          - event
          - protocol:
              version: "1"
               ...
            header:
              version: "1.0"
              ....
            body: {}
...
```

I hope this helps.
