### ISSUE TITLE
Can I capture message form event listener.

### ISSUE THREAD

**Issue by exodia0x** [ptejada/artillery-engine-socketio-v3#14]
Can we capture message form Event Listener after emit message to server or anyway to capture and show output it ? This is my example form postman

<img width="498" alt="image" src="https://github.com/ptejada/artillery-engine-socketio-v3/assets/38641615/96df63a6-bc03-4031-833f-68d4a088f17c">

<img width="693" alt="image" src="https://github.com/ptejada/artillery-engine-socketio-v3/assets/38641615/f2b5c447-c13e-420c-b2fd-0735167d4371">

**Comment by ptejada** [comment]
Yes. Almost all of the examples in this file do this 
https://github.com/ptejada/artillery-engine-socketio-v3/blob/master/test-app/artillery/default.yml

They assert what event should be received, but you can also capture it if needed.

**Comment by exodia0x** [comment]
Thank you. If i have 2 event message back but i need too capture only event message no.2 and all event same name. when i running more user some they capture in msg event no.1  sometime msg event no.2.  Have any way to fix capture for it?

And i see in debug log sometime msg even no.2 have delay so they just capture msg event no.1.

<img width="1241" alt="image" src="https://github.com/ptejada/artillery-engine-socketio-v3/assets/38641615/a850c894-4839-45fb-b4c5-64acfaf9cb30">


It's just capture first event and ignore second event message

Ex. code

```
        response:
          on: event
          capture:
            json: "$"
            as: "token"
      - log: "Event Message ===> {{ token }}"
```

**Comment by ptejada** [comment]
The response capture only handles the first matching event and will ignore everything else.

**Comment by exodia0x** [comment]
Thank you, Last please about loop and count i try to set 1 vus and i want to that 1 vus loop emit message with response match and i want to set emit 20, 30, or ..... emit per sec. But when i set to mtach it will 9-10 emit per sec and when i #match check  they emit around 6000++ emit per sec. So can i set about this section ?

Ex. code
```
scenarios:
  - name: " > Send Message and Check Respond == ACK"
    engine: socketio-v3
    flow:
      - loop:
        # - think: 1
        - emit:
            channel: "command"
            data:
              protocol:
              ..............
              body: {}
          response:
            on: event
            match:
              json: "$.protocol.service"
              value: "OK1234"
        count: 1000
```


And i want to make sure about in the picture section that is connection latency between client and server, right ?
<img width="604" alt="image" src="https://github.com/ptejada/artillery-engine-socketio-v3/assets/38641615/980cd7df-8793-42fc-956f-bcbfbaf318a7">

Because when i running it didn't show "socketio.response_time:"
![image](https://github.com/ptejada/artillery-engine-socketio-v3/assets/38641615/1d63f0c1-b584-4bf7-92a9-059841562425)
