### ISSUE TITLE
Run custom hook when an event is received

### ISSUE THREAD

**Issue by goodnessd** [ptejada/artillery-engine-socketio-v3#17]
Hello! I'm trying to connect a virtual user (VU) to my socket.io server that joins a room, waits for a message to be sent from the server to that room, and triggers a custom function on receiving that event.

The server has an external trigger that emits an event (`fooEvent`), and I want to inject a custom hook for some metric collection.

For example, I'd hope to do _something_ like this:

```
scenarios:
 - name: new socket.io client listening for event 
       flow:
        - emit: ["join", "room1"]
           response:
             on: fooEvent
             function: myCustomFunction
```

A version of this question has already been asked [here](https://github.com/ptejada/artillery-engine-socketio-v3/issues/14#issuecomment-1617282189), but I believe my use case it subtly different. 

All the examples that use `response` [here](https://github.com/ptejada/artillery-engine-socketio-v3/blob/master/test-app/artillery/default.yml) seem to be dependent on an `emit` first, and none of them use functions in `./functions.js` in the way that I'm trying to use it.
