### ISSUE TITLE
How to pass extraHeaders to scenario

### ISSUE THREAD

**Issue by maitrungduc1410** [ptejada/artillery-engine-socketio-v3#4]
Hi @ptejada ,

I'm trying to pass extra headers by using:
```yaml
scenarios:
  - engine: socketio-v3
    socketio:
      extraHeaders:
        Cookie: "test=123456"
....
```
But this is not working, `console.log` from server-side always returns `undefined`

Do you have any idea on this?

Thank you

**Comment by ptejada** [comment]
@maitrungduc1410 
I don't think this is an scenario that it is supported at the scenario flow level at the moment. You can can configure the client configuration from the `config.engines.socketio-v3` which will apply to all connections made. Ex:
```yml
config:
  target: "http://localhost:3000"
  phases:
    - duration: 30
      arrivalRate: 5
  engines:
   socketio-v3: 
     extraHeaders:
       Cookie: "test=123456"
scenarios:
  ...
```
