### ISSUE TITLE
Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by joshgeller** [ptejada/artillery-engine-socketio-v3#5]
Hello, thanks for your work on this package!

I installed artillery following the main docs, and the v3 engine using the readme.

My yaml file:

```
config:
  target: "http://localhost:3000"
  phases:
    - duration: 30
      arrivalRate: 5
  engines:
   socketio-v3: {}
  scenarios:
    - name: test
      engine: socketio-v3
      flow:
        - emit: ["test"]
```

When I run the test, I get the following error:

```
/Users/me/.nvm/versions/node/v16.4.0/lib/node_modules/artillery/lib/commands/run.js:318
  script.scenarios.forEach(function(scenario) {
                   ^

TypeError: Cannot read property 'forEach' of undefined
```

**Comment by ptejada** [comment]
@joshgeller 

Sorry for the delay. In case you have not figured it out yet your indentation is not correct. In YAML indentations are critical. The `scenarios` section should not be indented at all. In your example is under `config`.

This is the correct format:

```yml
config:
  target: "http://localhost:3000"
  phases:
    - duration: 30
      arrivalRate: 5
  engines:
   socketio-v3: {}
scenarios:
  - name: test
    engine: socketio-v3
    flow:
      - emit: ["test"]
```
