### ISSUE TITLE
Query parameters ignored

### ISSUE THREAD

**Issue by pjain11** [ptejada/artillery-engine-socketio-v3#6]
Here's how i'm using the config, i enabled debug logs and i don't see query parameters being passed in the request. 

config:
  target: "MY_URL"
  phases:
    - duration: 60
      arrivalRate: 5
  engines:
    socketio-v3:
      transports: ["websocket"] 
      query:
        Authorization: "MY_TOKEN"

**Comment by ptejada** [comment]
@pjain11 

Currently, this addon-engine is not configured to accept any options. Please set Socket.IO specification as documented here https://artillery.io/docs/guides/guides/socketio-reference.html#Socket-IO-specific-configuration

This plugin will use the same configs. Ex:
```yml
config:
  target: "MY_URL"
  phases:
    - duration: 60
       arrivalRate: 5
   engines:
     socketio-v3: {}
  socketio:
     transports: ["websocket"]
     query:
        Authorization: "MY_TOKEN"
```

I will make a compatibility update so client options can be set under `config.engines.sockerio-v3` as well.
