### ISSUE TITLE
Unable to emit data to Java netty-socketio

### ISSUE THREAD

**Issue by 29swastik** [ptejada/artillery-engine-socketio-v3#9]
I'm doing simple load test on netty-socketio Java, here when I run the load test I get "Client connected" message but looks like flows are not getting executed (I don't see any message in console after Client Connected) and all requests are getting timed out

**Output**
```
errors.Error: timeout: ......................................................... 425
vusers.created: ................................................................ 425
vusers.created_by_name.My sample scenario: ..................................... 425
vusers.failed: ................................................................. 425
```

**loadtest.yml**
```yml
config:
  target: "ws://localhost:9093"
  ws:
    maxRedirects: 25
  phases:
    - duration: 20
      arrivalRate: 5
      rampTo: 10
      name: "Warming up"
    - duration: 5
      arrivalRate: 10
      rampTo: 100
      name: "Max load"
  engines:
    socketio-v3: { }

scenarios:
  - name: My sample scenario
    engine: socketio-v3
    flow:
      - emit: ["data"]
```

**Java**
```java
@Component
public class ServerCommandLineRunner implements CommandLineRunner {

  private final SocketIOServer server;

  @Autowired
  public ServerCommandLineRunner(SocketIOServer server) {
    this.server = server;

    server.addConnectListener(new ConnectListener() {
      public void onConnect(SocketIOClient client) {
        System.out.println("Client connected: " + client.getSessionId());
      }
    });

    server.addDisconnectListener(new DisconnectListener() {
      public void onDisconnect(SocketIOClient client) {
        System.out.println("Client disconnected: " + client.getSessionId());
      }
    });

    server.addEventListener("chat", String.class, (client, data, ackRequest) -> {
      System.out.println("Message received: " + data);
      server.getBroadcastOperations().sendEvent("chat", data);
    });
  }

  @Override
  public void run(String... args) throws Exception {
    server.start();
  }
}
```

**Comment by ptejada** [comment]
It might be a compatibility issue. Are you sure your server supports the 3+ socket.io protocol?

How about the Artillery built-in support for socket.io, does it works with your server?

**Comment by 29swastik** [comment]
> It might be a compatibility issue. Are you sure your server supports the 3+ socket.io protocol?

Should be supported because I'm using latest version of [netty-socketio](https://github.com/mrniko/netty-socketio)
```java
    implementation 'com.corundumstudio.socketio:netty-socketio:1.7.23'
```


> How about the Artillery built-in support for socket.io, does it works with your server?

Same error even in built-in support, below is the yml I tried with built-in artillery support for socketio
```yml
config:
  target: "ws://localhost:9093"
  phases:
    - duration: 6
      arrivalRate: 25

scenarios:
  - name: "Emit an event"
    engine: socketio
    flow:
      - emit:
          channel: "chat"
          data: "hello"
 ```
